# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/
server:
  port: 8080


zeebe.client:
  cloud:
    region: syd-1
    clusterId: e2414fa7-9f91-4065-bf57-402406f8fe94
    clientId: aOh-ahMQ8_WO41E0fW.YS8u0XRY~XN4R
    clientSecret: rf0v.nutwxUDuoE43SOAjKnRIieN7Y3d83OHqmsuERf0Ic_URV67s_lVH2yHlu-R


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true

